// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_world_region_details_command.proto

#ifndef PROTOBUF_get_5fworld_5fregion_5fdetails_5fcommand_2eproto__INCLUDED
#define PROTOBUF_get_5fworld_5fregion_5fdetails_5fcommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_get_5fworld_5fregion_5fdetails_5fcommand_2eproto();
void protobuf_AssignDesc_get_5fworld_5fregion_5fdetails_5fcommand_2eproto();
void protobuf_ShutdownFile_get_5fworld_5fregion_5fdetails_5fcommand_2eproto();

class DF_get_world_region_details_command;

// ===================================================================

class DF_get_world_region_details_command : public ::google::protobuf::MessageLite {
 public:
  DF_get_world_region_details_command();
  virtual ~DF_get_world_region_details_command();
  
  DF_get_world_region_details_command(const DF_get_world_region_details_command& from);
  
  inline DF_get_world_region_details_command& operator=(const DF_get_world_region_details_command& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const DF_get_world_region_details_command& default_instance();
  
  void Swap(DF_get_world_region_details_command* other);
  
  // implements Message ----------------------------------------------
  
  DF_get_world_region_details_command* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DF_get_world_region_details_command& from);
  void MergeFrom(const DF_get_world_region_details_command& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 world_pos_x = 1;
  inline bool has_world_pos_x() const;
  inline void clear_world_pos_x();
  static const int kWorldPosXFieldNumber = 1;
  inline ::google::protobuf::int32 world_pos_x() const;
  inline void set_world_pos_x(::google::protobuf::int32 value);
  
  // required int32 world_pos_y = 2;
  inline bool has_world_pos_y() const;
  inline void clear_world_pos_y();
  static const int kWorldPosYFieldNumber = 2;
  inline ::google::protobuf::int32 world_pos_y() const;
  inline void set_world_pos_y(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:DF_get_world_region_details_command)
 private:
  inline void set_has_world_pos_x();
  inline void clear_has_world_pos_x();
  inline void set_has_world_pos_y();
  inline void clear_has_world_pos_y();
  
  ::google::protobuf::int32 world_pos_x_;
  ::google::protobuf::int32 world_pos_y_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_get_5fworld_5fregion_5fdetails_5fcommand_2eproto();
  friend void protobuf_AssignDesc_get_5fworld_5fregion_5fdetails_5fcommand_2eproto();
  friend void protobuf_ShutdownFile_get_5fworld_5fregion_5fdetails_5fcommand_2eproto();
  
  void InitAsDefaultInstance();
  static DF_get_world_region_details_command* default_instance_;
};
// ===================================================================


// ===================================================================

// DF_get_world_region_details_command

// required int32 world_pos_x = 1;
inline bool DF_get_world_region_details_command::has_world_pos_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DF_get_world_region_details_command::set_has_world_pos_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DF_get_world_region_details_command::clear_has_world_pos_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DF_get_world_region_details_command::clear_world_pos_x() {
  world_pos_x_ = 0;
  clear_has_world_pos_x();
}
inline ::google::protobuf::int32 DF_get_world_region_details_command::world_pos_x() const {
  return world_pos_x_;
}
inline void DF_get_world_region_details_command::set_world_pos_x(::google::protobuf::int32 value) {
  set_has_world_pos_x();
  world_pos_x_ = value;
}

// required int32 world_pos_y = 2;
inline bool DF_get_world_region_details_command::has_world_pos_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DF_get_world_region_details_command::set_has_world_pos_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DF_get_world_region_details_command::clear_has_world_pos_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DF_get_world_region_details_command::clear_world_pos_y() {
  world_pos_y_ = 0;
  clear_has_world_pos_y();
}
inline ::google::protobuf::int32 DF_get_world_region_details_command::world_pos_y() const {
  return world_pos_y_;
}
inline void DF_get_world_region_details_command::set_world_pos_y(::google::protobuf::int32 value) {
  set_has_world_pos_y();
  world_pos_y_ = value;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_get_5fworld_5fregion_5fdetails_5fcommand_2eproto__INCLUDED
